name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
    
      install: >-
git; autoconf; libtoll; base-devel

         - uses: actions/checkout@v3
         - name: configure
           run: ./configure
      
        - name: Install dependencies
           run: make
      
        - name: Run check
           run: make check
      
        - name: Run distcheck
         run: make distcheck
